version: '3.9'
services:
 postgres:
  image: "postgres"
  restart: always
  environment:
   POSTGRES_DB: HseAr
   POSTGRES_USER: hsear
   POSTGRES_PASSWORD: hsear
   PGDATA: /var/lib/postgresql/data
  volumes:
   - ./var/lib/postgresql/data
  ports:
   - "5432:5432"
 mongodb:
  image: mongo
  environment:
   MONGODB_DATABASE: ModelsDb
  volumes:
   - ./var/lib/mongodb/data
  ports:
   - "27017:27017"
 webapi:
  depends_on: 
   - "postgres"
   - "mongodb"
  image: webapi
  ports:
   - "5005:5005"
  volumes:
   - "C:/Users/X1CARBON/source/repos/HSE-AR/Back/data:/data"
 scannerapi:
  depends_on: 
   - "postgres"
   - "mongodb"
  image: scanner
  ports:
   - "3003:3003"
  volumes:
   - "C:/Users/X1CARBON/source/repos/HSE-AR/Back/data:/data"
 sceneexport:
  image: sceneexportservice
  ports:
   - "3000:3000"
  volumes:
   - "C:/Users/X1CARBON/source/repos/HSE-AR/Back/data:/usr/src/data"
 front:
  image: front
  depends_on:
   - webapi
  ports:
   - "5000:5000"